// src/elizabeth/src/components/Home.jsx
import React from 'react';

const { ipcRenderer } = window.require('electron');

const songs = [
    "Digital (Bandcamp)/Alestorm/Curse of the Crystal Coconut (Digital Deluxe)/Alestorm - Curse of the Crystal Coconut (Digital Deluxe) - 07 Pirate's Scorn.flac",
    "Digital (Bandcamp)/Alestorm/Curse of the Crystal Coconut (Digital Deluxe)/Alestorm - Curse of the Crystal Coconut (Digital Deluxe) - 08 Shit Boat (No Fans).flac",
    "Digital (Bandcamp)/Alestorm/Curse of the Crystal Coconut (Digital Deluxe)/Alestorm - Curse of the Crystal Coconut (Digital Deluxe) - 09 Pirate Metal Drinking Crew.flac"
];

function Home(){
    return(
        <div>
            <button onClick={()=> ipcRenderer.send('load-list', songs)}>Load Songs</button>
        </div>
    );
}

export default Home;

// src/renderer/components/Home.vue
<template>
    <div class="wrapper">
        eae, sou o home
        <button @click="load()">load songs</button>
    </div>
</template>

<script>
export default{
    name:'home',
    methods: {
        load(){
            this.$electron.ipcRenderer.send('load-list', [
                "Digital (Bandcamp)/Alestorm/Curse of the Crystal Coconut (Digital Deluxe)/Alestorm - Curse of the Crystal Coconut (Digital Deluxe) - 07 Pirate's Scorn.flac",
                "Digital (Bandcamp)/Alestorm/Curse of the Crystal Coconut (Digital Deluxe)/Alestorm - Curse of the Crystal Coconut (Digital Deluxe) - 08 Shit Boat (No Fans).flac",
                "Digital (Bandcamp)/Alestorm/Curse of the Crystal Coconut (Digital Deluxe)/Alestorm - Curse of the Crystal Coconut (Digital Deluxe) - 09 Pirate Metal Drinking Crew.flac",
            ]);
        }
    }
}
</script>
